import absolute_convective_instability_stability_hydrodynamic_theorem_canonical_lane_mathlib.GateLemmas
import absolute_convective_instability_stability_hydrodynamic_theorem_canonical_lane_mathlib.FinalTheorem
