import absolute_convective_instability_stability_hydrodynamic_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace absolute_convective_instability_stability_hydrodynamic_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end absolute_convective_instability_stability_hydrodynamic_theorem_canonical_lane_mathlib
end HautevilleHouse
